# Generated by Django 4.2.9 on 2024-04-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="allowance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="overtime_pay",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
