# Generated by Django 5.0.1 on 2024-05-02 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0003_employee_id_number_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='id_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_app.employee', to_field='id_number'),
        ),
    ]
