# Generated by Django 5.0.1 on 2024-05-07 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0002_alter_employee_allowance_alter_employee_overtime_pay'),
        ('payroll_app', '0004_alter_employee_id_number_alter_payslip_id_number'),
    ]

    operations = [
    ]
